# Generated by Django 2.1.1 on 2019-05-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=10)),
                ('created_by', models.IntegerField()),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
